In [278]:
import pandas as pd
import numpy as np

Import raw data.
Clean up blank lines and lines containing descriptions, legend, etc.

In [279]:
data2021 = pd.read_csv("raw_data/hcny_all_tables_2021.csv", skiprows=4)
data2020 = pd.read_csv("raw_data/hcny_all_tables_2020.csv", skiprows=4)
data2019 = pd.read_csv("raw_data/hcny_all_tables_2019.csv", skiprows=4)
data2018 = pd.read_csv("raw_data/hcny_all_tables_2018.csv", skiprows=4)
data2017 = pd.read_csv("raw_data/hcny_all_tables_2017.csv", skiprows=4)
data2016 = pd.read_csv("raw_data/hcny_all_tables_2016.csv", skiprows=4)

data2016 = data2016[data2016['State'].str.contains('Represents zero|Less than half|Tracheal mites|Includes') == False]
data2016 = data2016[data2016['State'].str.contains('Colony Health|colonies|Colonies|Percent|published') == False]
data2016 = data2016[data2016['State'].str.contains('Not applicable|Defined as any|Loss reported') == False]

data2017 = data2017[data2017['State'].str.contains('Represents zero|Less than half|Tracheal mites|Includes') == False]
data2017 = data2017[data2017['State'].str.contains('Colony Health|colonies|Colonies|Percent|published') == False]
data2017 = data2017[data2017['State'].str.contains('Not applicable|Defined as any|Loss reported') == False]

data2018 = data2018[data2018['State'].str.contains('Represents zero|Less than half|Tracheal mites|Includes') == False]
data2018 = data2018[data2018['State'].str.contains('Colony Health|colonies|Colonies|Percent|published') == False]
data2018 = data2018[data2018['State'].str.contains('Not applicable|Defined as any|Loss reported') == False]

data2019 = data2019[data2019['State'].str.contains('Represents zero|Less than half|Tracheal mites|Includes') == False]
data2019 = data2019[data2019['State'].str.contains('Colony Health|colonies|Colonies|Percent') == False]
data2019 = data2019[data2019['State'].str.contains('Not applicable|Defined as any|Loss reported') == False]

data2020 = data2020[data2020['State'].str.contains('Represents zero|Less than half|Tracheal mites|Includes') == False]
data2020 = data2020[data2020['State'].str.contains('Colony Health|colonies|Colonies|Percent') == False]
data2020 = data2020[data2020['State'].str.contains('Not applicable|Not available|Defined as any|Loss reported') == False]

data2021 = data2021[data2021['State'].str.contains('Represents zero|Less than half|Tracheal mites|Includes') == False]
data2021 = data2021[data2021['State'].str.contains('Colony Health|colonies|Colonies|Percent') == False]
data2021 = data2021[data2021['State'].str.contains('Not applicable|Defined as any|Loss reported') == False]

Drop superfluous index columns.

Get rid of rows with a NaN state.

Set State column as index.

In [280]:
data2016.drop(columns=['5', 'h'], axis=1, inplace=True)
data2016 = data2016[data2016['State'].notna()]
data2016.set_index('State')

data2017.drop(columns=['5', 'h'], axis=1, inplace=True)
data2017 = data2017[data2017['State'].notna()]
data2017.set_index('State')

data2018.drop(columns=['5', 'h'], axis=1, inplace=True)
data2018 = data2018[data2018['State'].notna()]
data2018.set_index('State')

data2019.drop(columns=['5', 'h'], axis=1, inplace=True)
data2019 = data2019[data2019['State'].notna()]
data2019.set_index('State')

data2020.drop(columns=['5', 'h'], axis=1, inplace=True)
data2020 = data2020[data2020['State'].notna()]
data2020.set_index('State')

data2021.drop(columns=['5', 'h'], axis=1, inplace=True)
data2021 = data2021[data2021['State'].notna()]
data2021.set_index('State')

,January 1,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
State,,,,,,,
Alabama,5500,7000,410,6,1900,780,11
Arizona,29000,31000,8500,27,3000,120,(Z)
Arkansas,16500,16500,1600,10,1800,30,(Z)
California,1350000,1710000,230000,13,240000,66000,4
Colorado,4500,13000,670,5,4000,500,4
...,...,...,...,...,...,...,...
Other States 4/,60.3,(Z),(Z),4.8,5.9,5.0,NaN
United States,48.7,12.8,5.5,12.3,11.3,3.9,NaN
Year,January-March,April-June,July-September,October-December,NaN,NaN,NaN
2020,105240,48270,78190,116910,NaN,NaN,NaN
2021,76930,49620,NaN,NaN,NaN,NaN,NaN

The date and time data has to be filled in chunks since the first six columns for all the states are listed for each quarter for the previous year, then the first six columns for the current year in the next set of rows, then the last six columns for all states for the previous year, then the last six for the current year.

In [281]:
# Insert year columns for each file
data2016.insert(1, 'year', np.nan)
data2017.insert(1, 'year', np.nan)
data2018.insert(1, 'year', np.nan)
data2019.insert(1, 'year', np.nan)
data2020.insert(1, 'year', np.nan)
data2021.insert(1, 'year', np.nan)

data2016.insert(2, 'quarter', np.nan)
data2017.insert(2, 'quarter', np.nan)
data2018.insert(2, 'quarter', np.nan)
data2019.insert(2, 'quarter', np.nan)
data2020.insert(2, 'quarter', np.nan)
data2021.insert(2, 'quarter', np.nan)

# Variables for inserting the year and quarter info
year_value_2015 = {'year': '2015'}
year_value_2016 = {'year': '2016'}
year_value_2017 = {'year': '2017'}
year_value_2018 = {'year': '2018'}
year_value_2019 = {'year': '2019'}
year_value_2020 = {'year': '2020'}
year_value_2021 = {'year': '2021'}
values_jan = {'quarter': 'Q1'}
values_apr = {'quarter': 'Q2'}
values_jul = {'quarter': 'Q3'}
values_oct = {'quarter': 'Q4'}

data2016.fillna(value=year_value_2015, limit=191, inplace=True)
data2016.fillna(value=year_value_2016, limit=48, inplace=True)
data2016.fillna(value=year_value_2015, limit=192, inplace=True)
data2016.fillna(value=year_value_2016, limit=48, inplace=True)

data2017.fillna(value=year_value_2016, limit=191, inplace=True)
data2017.fillna(value=year_value_2017, limit=96, inplace=True)
data2017.fillna(value=year_value_2016, limit=192, inplace=True)
data2017.fillna(value=year_value_2017, limit=96, inplace=True)

data2018.fillna(value=year_value_2017, limit=191, inplace=True)
data2018.fillna(value=year_value_2018, limit=96, inplace=True)
data2018.fillna(value=year_value_2017, limit=192, inplace=True)
data2018.fillna(value=year_value_2018, limit=96, inplace=True)

data2019.fillna(value=year_value_2018, limit=191, inplace=True)
data2019.fillna(value=year_value_2019, limit=96, inplace=True)
data2019.fillna(value=year_value_2018, limit=192, inplace=True)
data2019.fillna(value=year_value_2019, limit=96, inplace=True)

data2020.fillna(value=year_value_2019, limit=191, inplace=True)
data2020.fillna(value=year_value_2020, limit=96, inplace=True)
data2020.fillna(value=year_value_2019, limit=192, inplace=True)
data2020.fillna(value=year_value_2020, limit=96, inplace=True)

data2021.fillna(value=year_value_2020, limit=191, inplace=True)
data2021.fillna(value=year_value_2021, limit=96, inplace=True)
data2021.fillna(value=year_value_2020, limit=192, inplace=True)
data2021.fillna(value=year_value_2021, limit=96, inplace=True)

data2016.fillna(value=values_jan, limit=47, inplace=True)
data2016.fillna(value=values_apr, limit=48, inplace=True)
data2016.fillna(value=values_jul, limit=48, inplace=True)
data2016.fillna(value=values_oct, limit=48, inplace=True)
data2016.fillna(value=values_jan, limit=48, inplace=True)

data2016.fillna(value=values_jan, limit=48, inplace=True)
data2016.fillna(value=values_apr, limit=48, inplace=True)
data2016.fillna(value=values_jul, limit=48, inplace=True)
data2016.fillna(value=values_oct, limit=48, inplace=True)
data2016.fillna(value=values_jan, limit=48, inplace=True)

data2017.fillna(value=values_jan, limit=47, inplace=True)
data2017.fillna(value=values_apr, limit=48, inplace=True)
data2017.fillna(value=values_jul, limit=48, inplace=True)
data2017.fillna(value=values_oct, limit=48, inplace=True)
data2017.fillna(value=values_jan, limit=48, inplace=True)
data2017.fillna(value=values_apr, limit=48, inplace=True)

data2017.fillna(value=values_jan, limit=48, inplace=True)
data2017.fillna(value=values_apr, limit=48, inplace=True)
data2017.fillna(value=values_jul, limit=48, inplace=True)
data2017.fillna(value=values_oct, limit=48, inplace=True)
data2017.fillna(value=values_jan, limit=48, inplace=True)
data2017.fillna(value=values_apr, limit=48, inplace=True)

data2018.fillna(value=values_jan, limit=47, inplace=True)
data2018.fillna(value=values_apr, limit=48, inplace=True)
data2018.fillna(value=values_jul, limit=48, inplace=True)
data2018.fillna(value=values_oct, limit=48, inplace=True)
data2018.fillna(value=values_jan, limit=48, inplace=True)
data2018.fillna(value=values_apr, limit=48, inplace=True)

data2018.fillna(value=values_jan, limit=48, inplace=True)
data2018.fillna(value=values_apr, limit=48, inplace=True)
data2018.fillna(value=values_jul, limit=48, inplace=True)
data2018.fillna(value=values_oct, limit=48, inplace=True)
data2018.fillna(value=values_jan, limit=48, inplace=True)
data2018.fillna(value=values_apr, limit=48, inplace=True)

data2019.fillna(value=values_jan, limit=47, inplace=True)
data2019.fillna(value=values_apr, limit=48, inplace=True)
data2019.fillna(value=values_jul, limit=48, inplace=True)
data2019.fillna(value=values_oct, limit=48, inplace=True)
data2019.fillna(value=values_jan, limit=48, inplace=True)
data2019.fillna(value=values_apr, limit=48, inplace=True)

data2019.fillna(value=values_jan, limit=48, inplace=True)
data2019.fillna(value=values_apr, limit=48, inplace=True)
data2019.fillna(value=values_jul, limit=48, inplace=True)
data2019.fillna(value=values_oct, limit=48, inplace=True)
data2019.fillna(value=values_jan, limit=48, inplace=True)
data2019.fillna(value=values_apr, limit=48, inplace=True)

data2020.fillna(value=values_jan, limit=47, inplace=True)
data2020.fillna(value=values_apr, limit=48, inplace=True)
data2020.fillna(value=values_jul, limit=48, inplace=True)
data2020.fillna(value=values_oct, limit=48, inplace=True)
data2020.fillna(value=values_jan, limit=48, inplace=True)
data2020.fillna(value=values_apr, limit=48, inplace=True)

data2020.fillna(value=values_jan, limit=48, inplace=True)
data2020.fillna(value=values_apr, limit=48, inplace=True)
data2020.fillna(value=values_jul, limit=48, inplace=True)
data2020.fillna(value=values_oct, limit=48, inplace=True)
data2020.fillna(value=values_jan, limit=48, inplace=True)
data2020.fillna(value=values_apr, limit=48, inplace=True)

data2021.fillna(value=values_jan, limit=47, inplace=True)
data2021.fillna(value=values_apr, limit=48, inplace=True)
data2021.fillna(value=values_jul, limit=48, inplace=True)
data2021.fillna(value=values_oct, limit=48, inplace=True)
data2021.fillna(value=values_jan, limit=48, inplace=True)
data2021.fillna(value=values_apr, limit=48, inplace=True)

data2021.fillna(value=values_jan, limit=48, inplace=True)
data2021.fillna(value=values_apr, limit=48, inplace=True)
data2021.fillna(value=values_jul, limit=48, inplace=True)
data2021.fillna(value=values_oct, limit=48, inplace=True)
data2021.fillna(value=values_jan, limit=48, inplace=True)
data2021.fillna(value=values_apr, limit=48, inplace=True)

The first seven columns for each state are stored in different rows (the upper half of each csv file) from the second seven columns for each state (the lower half of each csv file). 
Cut the dataframe apart and specify the indices for both.
Set the column names for each now that they're separate, since the columns change names halfway through the larger sheet. Lastly, with the dataframes still split, remove the empty column from "bottom half" and the columns on renovated colonies, since they won't be used.

In [282]:
bottom_half_2016 = data2016.iloc[240:482]
top_half_2016 = data2016.iloc[:239]

bottom_half_2017 = data2017.iloc[288:578]
top_half_2017 = data2017.iloc[:287]

bottom_half_2018 = data2018.iloc[288:578]
top_half_2018 = data2018.iloc[:287]

bottom_half_2019 = data2019.iloc[288:]
top_half_2019 = data2019.iloc[:287]

bottom_half_2020 = data2020.iloc[288:]
top_half_2020 = data2020.iloc[:287]

bottom_half_2021 = data2021.iloc[288:]
top_half_2021 = data2021.iloc[:287]

bottom_half_2016.set_index(['State', 'year', 'quarter'])
top_half_2016.set_index(['State', 'year', 'quarter'])

bottom_half_2017.set_index(['State', 'year', 'quarter'])
top_half_2017.set_index(['State', 'year', 'quarter'])

bottom_half_2018.set_index(['State', 'year', 'quarter'])
top_half_2018.set_index(['State', 'year', 'quarter'])

bottom_half_2019.set_index(['State', 'year', 'quarter'])
top_half_2019.set_index(['State', 'year', 'quarter'])

bottom_half_2020.set_index(['State', 'year', 'quarter'])
top_half_2020.set_index(['State', 'year', 'quarter'])

bottom_half_2021.set_index(['State', 'year', 'quarter'])
top_half_2021.set_index(['State', 'year', 'quarter'])

first_columns = {'January 1': 'Starting colonies', 'Unnamed: 4': 'Maximum colonies', 'Unnamed: 5': 'Lost colonies', 'Unnamed: 6': 'Percent lost', 'Unnamed: 7': 'Added colonies', 'Unnamed: 8': 'Renovated colonies', 'Unnamed: 9': 'Percent renovated'}
second_columns = {'January 1': 'Varroa mites', 'Unnamed: 4': 'Other pests', 'Unnamed: 5': 'Diseases', 'Unnamed: 6': 'Pesticides', 'Unnamed: 7': 'Other', 'Unnamed: 8': 'Unknown', 'Unnamed: 9': 'empty'}
alt_first_columns = {'Unnamed: 3': 'Starting colonies', 'Unnamed: 4': 'Maximum colonies', 'Unnamed: 5': 'Lost colonies', 'Unnamed: 6': 'Percent lost', 'Unnamed: 7': 'Added colonies', 'Unnamed: 8': 'Renovated colonies', 'Unnamed: 9': 'Percent renovated'}
alt_second_columns = {'Unnamed: 3': 'Varroa mites', 'Unnamed: 4': 'Other pests', 'Unnamed: 5': 'Diseases', 'Unnamed: 6': 'Pesticides', 'Unnamed: 7': 'Other', 'Unnamed: 8': 'Unknown', 'Unnamed: 9': 'empty'}

top_half_2016.rename(alt_first_columns, axis=1, inplace=True)
bottom_half_2016.rename(alt_second_columns, axis=1, inplace=True)

top_half_2017.rename(alt_first_columns, axis=1, inplace=True)
bottom_half_2017.rename(alt_second_columns, axis=1, inplace=True)

top_half_2018.rename(alt_first_columns, axis=1, inplace=True)
bottom_half_2018.rename(alt_second_columns, axis=1, inplace=True)

top_half_2019.rename(first_columns, axis=1, inplace=True)
bottom_half_2019.rename(second_columns, axis=1, inplace=True)

top_half_2020.rename(first_columns, axis=1, inplace=True)
bottom_half_2020.rename(second_columns, axis=1, inplace=True)

top_half_2021.rename(first_columns, axis=1, inplace=True)
bottom_half_2021.rename(second_columns, axis=1, inplace=True)

top_half_2016.drop(['Renovated colonies', 'Percent renovated'], inplace=True, axis=1)
bottom_half_2016.drop('empty', inplace=True, axis=1)

top_half_2017.drop(['Renovated colonies', 'Percent renovated'], inplace=True, axis=1)
bottom_half_2017.drop('empty', inplace=True, axis=1)

top_half_2018.drop(['Renovated colonies', 'Percent renovated'], inplace=True, axis=1)
bottom_half_2018.drop('empty', inplace=True, axis=1)

top_half_2019.drop(['Renovated colonies', 'Percent renovated'], inplace=True, axis=1)
bottom_half_2019.drop('empty', inplace=True, axis=1)

top_half_2020.drop(['Renovated colonies', 'Percent renovated'], inplace=True, axis=1)
bottom_half_2020.drop('empty', inplace=True, axis=1)

top_half_2021.drop(['Renovated colonies', 'Percent renovated'], inplace=True, axis=1)
bottom_half_2021.drop('empty', inplace=True, axis=1)

/Users/tgreen/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
/Users/tgreen/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Now that the two datasets have indices and correct column labels, join them together in one set.

In [283]:
merged_data2021 = pd.merge_ordered(top_half_2021, bottom_half_2021, on=['State', 'year', 'quarter'])
merged_data2020 = pd.merge_ordered(top_half_2020, bottom_half_2020, on=['State', 'year', 'quarter'])
merged_data2019 = pd.merge_ordered(top_half_2019, bottom_half_2019, on=['State', 'year', 'quarter'])
merged_data2018 = pd.merge_ordered(top_half_2018, bottom_half_2018, on=['State', 'year', 'quarter'])
merged_data2017 = pd.merge_ordered(top_half_2017, bottom_half_2017, on=['State', 'year', 'quarter'])
merged_data2016 = pd.merge_ordered(top_half_2016, bottom_half_2016, on=['State', 'year', 'quarter'])

Clean up the last few junk rows in each sheet.

In [284]:
merged_data2016 = merged_data2016[merged_data2016['State'].str.contains('State|Year|Quarter|Item|2016') == False]
merged_data2017 = merged_data2017[merged_data2017['State'].str.contains('State|Year|Quarter|Item|2016|2017') == False]
merged_data2018 = merged_data2018[merged_data2018['State'].str.contains('State|Year|Quarter|Item|2017|2018') == False]
merged_data2019 = merged_data2019[merged_data2019['State'].str.contains('State|Year|Quarter|Item|2018|2019') == False]
merged_data2020 = merged_data2020[merged_data2020['State'].str.contains('State|Year|Quarter|Item|2019|2020') == False]
merged_data2021 = merged_data2021[merged_data2021['State'].str.contains('State|Year|Quarter|Item|2020|2021') == False]

merged_2016_2017 = pd.concat([merged_data2016, merged_data2017])
merged_2016_2018 = pd.concat([merged_2016_2017, merged_data2018])
merged_2016_2019 = pd.concat([merged_2016_2018, merged_data2019])
merged_2016_2020 = pd.concat([merged_2016_2019, merged_data2020])
all_merged = pd.concat([merged_2016_2020, merged_data2021])

all_merged.to_csv('all_merged.csv')